"""
GitHub API module for posting results back to issues.
"""

import os
import logging
from typing import Optional
from github import Github, GithubException

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class GitHubAPI:
    """GitHub API client for posting results."""
    
    def __init__(self, token: Optional[str] = None):
        self.token = token or os.getenv('GITHUB_TOKEN')
        self.client = None
        
        if self.token:
            try:
                self.client = Github(self.token)
                logger.info("GitHub API initialized")
            except Exception as e:
                logger.error(f"Failed to initialize GitHub API: {e}")
    
    def post_comment(self, repo_name: str, issue_number: int, comment: str) -> bool:
        """Post a comment to a GitHub issue."""
        if not self.client:
            logger.error("GitHub client not initialized")
            return False
        
        try:
            repo = self.client.get_repo(repo_name)
            issue = repo.get_issue(issue_number)
            issue.create_comment(comment)
            logger.info(f"Posted comment to issue #{issue_number}")
            return True
        except GithubException as e:
            logger.error(f"Error posting comment: {e}")
            return False
    
    def add_label(self, repo_name: str, issue_number: int, label: str) -> bool:
        """Add a label to an issue."""
        if not self.client:
            logger.error("GitHub client not initialized")
            return False
        
        try:
            repo = self.client.get_repo(repo_name)
            issue = repo.get_issue(issue_number)
            issue.add_to_labels(label)
            logger.info(f"Added label '{label}' to issue #{issue_number}")
            return True
        except GithubException as e:
            logger.error(f"Error adding label: {e}")
            return False
    
    def get_issue_body(self, repo_name: str, issue_number: int) -> Optional[str]:
        """Get the body of an issue."""
        if not self.client:
            logger.error("GitHub client not initialized")
            return None
        
        try:
            repo = self.client.get_repo(repo_name)
            issue = repo.get_issue(issue_number)
            return issue.body
        except GithubException as e:
            logger.error(f"Error getting issue body: {e}")
            return None
    
    def create_summary_comment(self, markdown: str, mermaid: str = "") -> str:
        """Create a formatted summary comment for GitHub."""
        comment = "# 🔬 Research Agent Results\n\n"
        comment += "Your research has been completed! Here's a summary of the findings:\n\n"
        
        # Add a condensed version of the markdown
        lines = markdown.split('\n')
        summary_lines = []
        in_summary = False
        
        for line in lines:
            if '## Executive Summary' in line:
                in_summary = True
                continue
            if in_summary and line.startswith('##'):
                break
            if in_summary and line.strip():
                summary_lines.append(line)
        
        if summary_lines:
            comment += '\n'.join(summary_lines) + '\n\n'
        
        # Add mermaid diagram if available
        if mermaid:
            comment += "## Knowledge Graph\n\n"
            comment += "```mermaid\n"
            comment += mermaid
            comment += "\n```\n\n"
        
        # Add download instructions
        comment += "## 📥 Download Full Report\n\n"
        comment += "The complete research report is available in multiple formats:\n"
        comment += "- 📄 Markdown report\n"
        comment += "- 📊 JSON data\n"
        comment += "- 🌐 HTML dashboard\n"
        comment += "- 📚 BibTeX citations\n"
        comment += "- 📈 CSV data\n\n"
        comment += "Check the workflow run artifacts to download these files.\n\n"
        comment += "---\n"
        comment += "*Generated by Autonomous Research Agent*"
        
        return comment
